# Adaptación del tema "Everforest" al tema "Kanagawa Dragon"

[[colors.indexed_colors]]
color = "#b98d7b"  # dragonOrange2
index = 16

[[colors.indexed_colors]]
color = "#c4746e"  # dragonRed
index = 17

[colors.bright]
black = "#625e5a"   # dragonBlack6
blue = "#8ba4b0"    # dragonBlue2
cyan = "#8ea4a2"    # dragonAqua
green = "#87a987"   # dragonGreen
magenta = "#8992a7" # dragonViolet
red = "#c4746e"     # dragonRed
white = "#c5c9c5"   # dragonWhite
yellow = "#c4b28a"  # dragonYellow

[colors.cursor]
cursor = "#c5c9c5"  # dragonWhite
text = "#c5c9c5"    # dragonWhite

[colors.normal]
black = "#12120f"   # dragonBlack1
blue = "#658594"    # dragonBlue
cyan = "#8ea4a2"    # dragonAqua
green = "#87a987"   # dragonGreen
magenta = "#a292a3" # dragonPink
red = "#c4746e"     # dragonRed
white = "#c5c9c5"   # dragonWhite
yellow = "#c4b28a"  # dragonYellow

[colors.primary]
background = "#181616"  # dragonBlack3 con 98% de opacidad
foreground = "#c5c9c5"    # dragonWhite

[colors.selection]
background = "#282727"    # dragonBlack4
text = "#c5c9c5"          # dragonWhite

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "IosevkaTerm NFM"

[window]
option_as_alt = "Both"
opacity = 0.9

[env]
TERM = "xterm-256color"

# Uncomment for Windows
#[shell]
#program = "wsl.exe"
#args = ["--cd","~"]

