format = """\
[╭─](fg:arrow)\
$username\
$os\
$git_branch\
(at $directory)\
$cmd_duration\
($python $conda $nodejs $c $rust $java $bun $zig)\
[\n╰─](fg:arrow)$character\
"""

# Desactivar la línea en blanco al inicio del prompt
add_newline = true

# Ajustes de color y estilo Kanagawa Dragon
palette = "kanagawa_dragon"

[palettes.kanagawa_dragon]
arrow = "#DCD7BA"     # Color hueso claro, suave y visible
os = "#C4B28A"        # Tono amarillo cálido de dragonYellow
directory = "#8BA4B0" # Azul celeste suave, dragonBlue2
git = "#C4746E"       # Rojo suave, dragonRed
duration = "#957FB8"  # Púrpura suave, oniViolet
text_color = "#C5C9C5" # Color claro, dragonWhite
text_light = "#2A2A37" # Gris oscuro, sumiInk4

# Icono del bigote rosa para el prompt
[character]
success_symbol = "[󱗞](fg:#A3BE8C)" # Bigote en tono rosa oscuro
error_symbol = "[󱗞](fg:red)"       # Bigote en rojo si hay error

# Configuración del usuario
[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[󱗞 $user](fg:$style) ' # Bigote antes del nombre de usuario
disabled = false
show_always = true

# Configuración del directorio
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

# Otros módulos mantienen los colores del tema
[time]
format = "at [󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
format = "took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "via [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " " # Rama con toque oriental

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text_color bg:git"

[docker_context]
disabled=true
symbol = " "

[nodejs]
format = "[$symbol$version ]($style)"
symbol = " "
version_format = "${raw}"
disabled=false

[python]
disabled=false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = " "
version_format = "${raw}"

[conda]
format = "[$symbol$environment ]($style)"
ignore_base = false
disabled = true
symbol = " "

[java]
format = "[$symbol$version ]($style)"
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = "[$symbol($version(-$name)) ]($style)"
symbol = " "
version_format = "${raw}"
disabled = false

[rust]
format ="[$symbol$version ]($style)"
symbol = " "
version_format = "${raw}"
disabled=false

[zig]
format = '([$symbol($version )]($style))'
version_format = "${raw}"
disabled=false

[bun]
format = '([$symbol($version )]($style))'
version_format = "${raw}"
disabled=false

